baseurl = "http://45.55.251.5/"
languageCode = "en-us"
title = "Pigeon Hill Brewing Co."
theme = "beer"
GoogleAnalytics = "XX-00000000-0"
Copyright = "© 2015 Pigeon Hill Brewing Company, LLC. All Rights Reserved"
disableRSS = true

[params]
  youarehere = "Pigeon Hill Brewing Co."
  tagline = "Always Pure And Without Drugs or Poison"
  heroquote = "Steeped in Tradition.  Brewed in Perfection."
  heroquoteauthor = "Proudly Brewed in Downtown Muskegon, MI"
  description = "At Pigeon Hill Brewing Company, we believe in: Our hometown, Muskegon, MI; Our Community; and Excellent Craft Beer. We hope to see you in the taproom."
  ontap = ["Shifting Sands – IPA", "LMFAO - Nitro Stout", "Stage 5 Clinger - Amber", "Double Dunes - Double IPA", "Walter Blondale - Blonde Ale", "Renegade White - Double IPA", "Renegade Red - Double IPA"]
  bottlestock = ["Feisty Latina Mexican Stout", "Your Mom on French Toast"]
  growlerstatus = "We do offer growler and howler fills from the brewery so fill 'er on up!"
  team = ["Jonathan Crawford", "Carl Davidson", "Arthur Porter", "Andrea Bell", "Emily Jensen", "Crystal Barrett", "Brody Berson"]
  twitter = "pigeonhillbrew"
  facebook = "PigeonHillBrew"
  instagram = "pigeonhillbrew"
  untappd = "PigeonHillBrew"
  untappedID = "1405081"
  beeradvocate = "20681"
  baScore = "92"
  baTitle = ""
  baRatings = "30"
  phone = "(231) 375-5184"
  address1 = "500 W Western Ave Suite 1"
  address2 = "Muskegon, MI 49440"
  addresshelp = "Just East of Exit 114 off U.S. 31."
  googlemaps = "https://goo.gl/maps/iYGcUDE1nVu"
  email = "info@pigeonhillbrew.com"

[[params.hours]]
  days = "Monday-Thursday"
  hours = "3pm-10pm"
[[params.hours]]
  days = "Friday-Saturday"
  hours = "12pm-12am"
[[params.hours]]
  days = "Sunday"
  hours = "12pm-8pm"
[[params.taproom]]
    type = "tours"
    content = "We do not currently offer brewery tours, but stop by our taproom and get an up-close view of the brewery operations through the glass windows."
[[params.taproom]]
    type = "description"
    content = "We are proud to be a Muskegon microbrewery, and we strive to highlight local history throughout our taproom.  Both our production facility and taproom are located in beautiful downtown Muskegon, MI.  In our taproom, you will find all of the beers and non-alcohol beverages listed on our taplist. Snacks from local vendors (including “Belly Full of Hoppyness,” which uses our beer) are available, as well as bottles of our beer, merchandise and gift certificates. For those looking for a full meal, you are welcome to bring food with you or order delivery (we have menus on site)."
[[params.taproom]]
    type = "holidays"
    content = "The taproom is closed on the following holidays: New Year's Day, Easter, Memorial Day, July 4th, Labor Day, Thanksgiving, and Christmas Day."