baseurl = "http://45.55.251.5/"
languageCode = "en-us"
title = "Pigeon Hill Brewing Co."
theme = "beer"
GoogleAnalytics = "XX-00000000-0"
Copyright = "© 2015 Pigeon Hill Brewing Company, LLC. All Rights Reserved"
disableRSS = true

[params]
  youarehere = "Pigeon Hill Brewing Co."
  tagline = "Always Pure And Without Drugs or Poison"
  heroquote = "Steeped in Tradition.  Brewed in Perfection."
  heroquoteauthor = "Proudly Brewed in Downtown Muskegon, MI"
  description = "At Pigeon Hill Brewing Company, we believe in: Our hometown, Muskegon, MI; Our Community; and Excellent Craft Beer. We hope to see you in the taproom."
  ontap = ["Shifting Sands – IPA", "LMFAO - Nitro Stout", "Stage 5 Clinger - Amber", "Double Dunes - Double IPA", "Walter Blondale - Blonde Ale", "Renegade White - Double IPA", "Renegade Red - Double IPA"]
  totaltaps = 8
  bottlestock = ["Feisty Latina Mexican Stout", "Your Mom on French Toast"]
  team = ["Jonathan Crawford", "Carl Davidson", "Arthur Porter", "Andrea Bell", "Emily Jensen", "Crystal Barrett", "Brody Berson"]
  twitter = "pigeonhillbrew"
  facebook = "PigeonHillBrew"
  instagram = "pigeonhillbrew"
  untappd = "PigeonHillBrew"
  untappedID = "1405081"
  beeradvocate = "20681"
  baScore = "92"
  baTitle = ""
  baRatings = "30"
  phone = "(231) 375-5184"
  address1 = "500 W Western Ave Suite 1"
  address2 = "Muskegon, MI 49440"
  addresshelp = "Just East of Exit 114 off U.S. 31."
  googlemaps = "https://goo.gl/maps/iYGcUDE1nVu"
  email = "info@pigeonhillbrew.com"

[[params.hours]]
  days = "Monday-Thursday"
  hours = "3pm-10pm"
[[params.hours]]
  days = "Friday-Saturday"
  hours = "12pm-12am"
[[params.hours]]
  days = "Sunday"
  hours = "12pm-8pm"